server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bishe?serverTimezone=GMT%2b8
    username: root
    password: 315581

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/毕设/代码/files/

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/bishe?serverTimezone=GMT%2b8
#spring.datasource.username=root

#spring.datasource.password=315581